source/Nidan/Nidan.Data/Models/NidanDatabase.cs
source/Nidan/Nidan.Data/NidanDataService.cs
source/Nidan/Nidan.Entity/CasteCategory.cs
source/Nidan/Nidan.Entity/Centre.cs
source/Nidan/Nidan.Entity/Colour.cs
source/Nidan/Nidan.Entity/Course.cs
source/Nidan/Nidan.Entity/Enquiry.cs
source/Nidan/Nidan.Entity/FollowUp.cs
source/Nidan/Nidan.Entity/HowDidYouKnowAbout.cs
source/Nidan/Nidan.Entity/Mobilization.cs
source/Nidan/Nidan.Entity/Occupation.cs
source/Nidan/Nidan.Entity/Partials/Enquiry.cs
source/Nidan/Nidan.Entity/Qualification.cs
source/Nidan/Nidan.Entity/Religion.cs
source/Nidan/Nidan.Entity/Site.cs
source/Nidan/Nidan/Controllers/EnquiryController.cs
source/Nidan/Nidan/Views/Enquiry/Edit.cshtml
source/Nidan/Nidan/Views/Enquiry/Index.cshtml
source/Nidan/Nidan/Views/Enquiry/_Enquiry.cshtml
source/Nidan/Nidan/Views/Mobilization/_Mobilization.cshtml

Enquiry Changes

---

source/Nidan/Nidan.Business/Dto/Extensions.cs
source/Nidan/Nidan.Business/Interfaces/INidanBusinessService.cs
source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan.Data/Models/NidanDatabase.cs
source/Nidan/Nidan.Entity/Enquiry.cs
source/Nidan/Nidan.Entity/Mobilization.cs
source/Nidan/Nidan.Entity/MobilizationType.cs
source/Nidan/Nidan.Entity/Organisation.cs
source/Nidan/Nidan.Entity/Partials/Enquiry.cs
source/Nidan/Nidan.Entity/Partials/Mobilization.cs
source/Nidan/Nidan/Controllers/MobilizationController.cs
source/Nidan/Nidan/Models/MobilizationViewModel.cs
source/Nidan/Nidan/Views/Enquiry/_Enquiry.cshtml
source/Nidan/Nidan/Views/Mobilization/Index.cshtml
source/Nidan/Nidan/Views/Mobilization/Upload.cshtml
source/Nidan/Nidan/Views/Mobilization/_Mobilization.cshtml

MobilizationType & Upload view added

MobilizationType & Upload view added

---

DB/CreateTable Counselling.sql
source/Nidan/Nidan.Business/Interfaces/INidanBusinessService.cs
source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan.Data/Interfaces/INidanDataService.cs
source/Nidan/Nidan.Data/Models/NidanDatabase.cs
source/Nidan/Nidan.Data/NidanDataService.cs
source/Nidan/Nidan.Entity/Counselling.cs
source/Nidan/Nidan.Entity/CounsellingSearchField.cs
source/Nidan/Nidan.Entity/Partials/Counselling.cs
source/Nidan/Nidan.Entity/Partials/FollowUp.cs
source/Nidan/Nidan.Entity/Partials/Mobilization.cs
source/Nidan/Nidan.Entity/Personnel.cs
source/Nidan/Nidan.Entity/Sector.cs
source/Nidan/Nidan/Controllers/CounsellingController.cs
source/Nidan/Nidan/Controllers/EnquiryController.cs
source/Nidan/Nidan/Controllers/HomeController.cs
source/Nidan/Nidan/Models/CounsellingViewModel.cs
source/Nidan/Nidan/Models/HomeViewModel.cs
source/Nidan/Nidan/Scripts/Angular/Controllers/CounsellingController.js
source/Nidan/Nidan/Scripts/Angular/Services/CounsellingService.js
source/Nidan/Nidan/Views/Centre/Create.cshtml
source/Nidan/Nidan/Views/Counselling/Edit.cshtml
source/Nidan/Nidan/Views/Counselling/Index.cshtml
source/Nidan/Nidan/Views/FollowUp/Index.cshtml
source/Nidan/Nidan/Views/FollowUp/_FollowUp.cshtml
source/Nidan/Nidan/Views/Home/Index.cshtml
source/Nidan/Nidan/Views/Shared/_Counselling.cshtml

Counselling Searchbydate and Search Added

Counselling Searchbydate and Search Added

---

DB/CreateTable_Enquiry_Script.sql
source/Nidan/Nidan.Entity/Enquiry.cs
source/Nidan/Nidan.Entity/Partials/Enquiry.cs
source/Nidan/Nidan/Controllers/EnquiryController.cs
source/Nidan/Nidan/Models/EnquiryViewModel.cs
source/Nidan/Nidan/Views/Counselling/Edit.cshtml
source/Nidan/Nidan/Views/Enquiry/Edit.cshtml
source/Nidan/Nidan/Views/Enquiry/Index.cshtml
source/Nidan/Nidan/Views/Enquiry/_Enquiry.cshtml
source/Nidan/Nidan/Views/FollowUp/Index.cshtml

ConversionProspect in Enquiry & CreateTable_Enquiry_Script

ConversionProspect in Enquiry & CreateTable_Enquiry_Script

---

source/Nidan/Nidan.Entity/Counselling.cs
source/Nidan/Nidan.Entity/Enquiry.cs
source/Nidan/Nidan.Entity/FollowUp.cs
source/Nidan/Nidan.Entity/Mobilization.cs
source/Nidan/Nidan.Entity/Partials/Counselling.cs
source/Nidan/Nidan.Entity/Partials/Enquiry.cs
source/Nidan/Nidan.Entity/Partials/Mobilization.cs
source/Nidan/Nidan/Scripts/Angular/Controllers/CounsellingController.js
source/Nidan/Nidan/Scripts/Angular/Controllers/FollowUpController.js
source/Nidan/Nidan/Views/Counselling/Edit.cshtml
source/Nidan/Nidan/Views/Enquiry/Create.cshtml
source/Nidan/Nidan/Views/Enquiry/Edit.cshtml
source/Nidan/Nidan/Views/Enquiry/_Enquiry.cshtml
source/Nidan/Nidan/Views/FollowUp/Index.cshtml
source/Nidan/Nidan/Views/FollowUp/_FollowUp.cshtml
source/Nidan/Nidan/Views/Mobilization/Edit.cshtml
source/Nidan/Nidan/Views/Mobilization/_Mobilization.cshtml
source/Nidan/Nidan/Views/Shared/_Counselling.cshtml

Minor Changes in all forms

---

source/Nidan/Nidan.Entity/Centre.cs
source/Nidan/Nidan.Entity/Partials/Room.cs
source/Nidan/Nidan.Entity/Room.cs
source/Nidan/Nidan/Controllers/HomeController.cs
source/Nidan/Nidan/Controllers/MobilizationController.cs
source/Nidan/Nidan/Controllers/RoomController.cs
source/Nidan/Nidan/Controllers/SubjectController.cs
source/Nidan/Nidan/Controllers/TrainerController.cs
source/Nidan/Nidan/Models/RoomViewModel.cs
source/Nidan/Nidan/Models/SubjectViewModel.cs
source/Nidan/Nidan/Models/TrainerViewModel.cs
source/Nidan/Nidan/Scripts/Angular/Controllers/DocumentController.js
source/Nidan/Nidan/Scripts/Angular/Controllers/RoomController.js
source/Nidan/Nidan/Scripts/Angular/Services/RoomService.js
source/Nidan/Nidan/Views/Room/Create.cshtml
source/Nidan/Nidan/Views/Room/Edit.cshtml
source/Nidan/Nidan/Views/Room/Index.cshtml
source/Nidan/Nidan/Views/Room/_Room.cshtml
source/Nidan/Nidan/Views/Shared/_Layout.cshtml
source/Nidan/Nidan/Views/Shared/_MobilizationBulkUpload.cshtml
source/Nidan/Nidan/Views/Shared/_SessionDocument.cshtml
source/Nidan/Nidan/Views/Shared/_TrainerDocument.cshtml
source/Nidan/Nidan/Views/Subject/Edit.cshtml
source/Nidan/Nidan/Views/Subject/Upload.cshtml
source/Nidan/Nidan/Views/Trainer/Edit.cshtml
source/Nidan/Nidan/Views/Trainer/_Trainer.cshtml

Class Room Implemented & Trainer Document Upload & Subject - Sub modules Upload

Class Room Implemented & Trainer Document Upload & Subject - Sub modules Upload

---

source/Nidan/Nidan.Business/Interfaces/INidanBusinessService.cs
source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan.Data/NidanDataService.cs
source/Nidan/Nidan.Entity/Batch.cs
source/Nidan/Nidan.Entity/Room.cs
source/Nidan/Nidan.Entity/Trainer.cs
source/Nidan/Nidan/Controllers/BatchController.cs
source/Nidan/Nidan/Models/BatchViewModel.cs
source/Nidan/Nidan/Scripts/Angular/Controllers/TrainerController.js
source/Nidan/Nidan/Scripts/Angular/Services/TrainerService.js
source/Nidan/Nidan/Views/Batch/Create.cshtml
source/Nidan/Nidan/Views/Batch/Edit.cshtml
source/Nidan/Nidan/Views/Batch/Index.cshtml
source/Nidan/Nidan/Views/Batch/_Batch.cshtml
source/Nidan/Nidan/Views/Course/_CourseInstallmentList.cshtml
source/Nidan/Nidan/Views/RegistrationPaymentReceipt/Edit.cshtml

BatchTrainer

---

source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan.Data/Models/NidanDatabase.cs
source/Nidan/Nidan.Entity/FollowUp.cs
source/Nidan/Nidan.Entity/Partials/Enquiry.cs
source/Nidan/Nidan/Controllers/EnquiryController.cs
source/Nidan/Nidan/Models/EnquiryViewModel.cs
source/Nidan/Nidan/Scripts/Angular/Controllers/EnquiryController.js
source/Nidan/Nidan/Views/Enquiry/Create.cshtml
source/Nidan/Nidan/Views/Enquiry/_Enquiry.cshtml
source/Nidan/Nidan/Views/Mobilization/Create.cshtml
source/Nidan/Nidan/Views/Mobilization/Index.cshtml
source/Nidan/Nidan/Views/Mobilization/_Mobilization.cshtml

Enquiry and followup small changes

Enquiry and followup small changes

---

source/Nidan/Nidan.Business/Interfaces/INidanBusinessService.cs
source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan.Data/Models/NidanDatabase.cs
source/Nidan/Nidan.Data/NidanDataService.cs
source/Nidan/Nidan.Entity/Course.cs
source/Nidan/Nidan.Entity/FollowUp.cs
source/Nidan/Nidan/Controllers/AdmissionController.cs
source/Nidan/Nidan/Controllers/RegistrationPaymentReceiptController.cs
source/Nidan/Nidan/Models/AdmissionViewModel.cs
source/Nidan/Nidan/Models/EnquiryViewModel.cs
source/Nidan/Nidan/Models/RegistrationPaymentReceiptViewModel.cs
source/Nidan/Nidan/Scripts/Angular/Controllers/AdmissionController.js
source/Nidan/Nidan/Scripts/Angular/Services/AdmissionService.js
source/Nidan/Nidan/Views/Admission/Create.cshtml
source/Nidan/Nidan/Views/Admission/Edit.cshtml
source/Nidan/Nidan/Views/Admission/Index.cshtml
source/Nidan/Nidan/Views/Admission/_Admission.cshtml
source/Nidan/Nidan/Views/RegistrationPaymentReceipt/Create.cshtml
source/Nidan/Nidan/Views/RegistrationPaymentReceipt/Edit.cshtml
source/Nidan/Nidan/Views/RegistrationPaymentReceipt/Index.cshtml
source/Nidan/Nidan/Views/RegistrationPaymentReceipt/_RegistrationFromEnquiry.cshtml
source/Nidan/Nidan/Views/RegistrationPaymentReceipt/_RegistrationPaymentReceipt.cshtml
source/Nidan/Nidan/Views/Shared/_Layout.cshtml

Admission UI (Incomplete)

---

source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan.Data/NidanDataService.cs
source/Nidan/Nidan.Entity/Admission.cs
source/Nidan/Nidan/Controllers/AdmissionController.cs
source/Nidan/Nidan/Models/AdmissionViewModel.cs
source/Nidan/Nidan/Views/Admission/Create.cshtml
source/Nidan/Nidan/Views/Admission/Edit.cshtml
source/Nidan/Nidan/Views/Admission/Index.cshtml
source/Nidan/Nidan/Views/Admission/_Admission.cshtml

Admission CRUD (Without Logic)

Admission CRUD (Without Logic)

---

source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan.Entity/Partials/FollowUp.cs
source/Nidan/Nidan/Views/FollowUp/_FollowUp.cshtml
source/Nidan/Nidan/Views/Shared/_Counselling.cshtml

FollowUp and Counselling UI Changes

FollowUp and Counselling UI Changes

---

source/Nidan/Nidan.Business/Interfaces/INidanBusinessService.cs
source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan.Data/Interfaces/INidanDataService.cs
source/Nidan/Nidan.Data/NidanDataService.cs
source/Nidan/Nidan.Entity/CandidateInstallment.cs
source/Nidan/Nidan.Entity/Course.cs
source/Nidan/Nidan.Entity/CourseInstallment.cs
source/Nidan/Nidan/Controllers/AdmissionController.cs
source/Nidan/Nidan/Views/Admission/Create.cshtml
source/Nidan/Nidan/Views/Admission/Index.cshtml
source/Nidan/Nidan/Views/Admission/_Admission.cshtml

Admission Create

---

source/Nidan/Nidan.Business/Interfaces/INidanBusinessService.cs
source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan/Controllers/CandidateFeeController.cs
source/Nidan/Nidan/Models/CandidateFeeViewModel.cs
source/Nidan/Nidan/Scripts/Angular/Controllers/CandidateFeeController.js
source/Nidan/Nidan/Scripts/Angular/Controllers/RegistrationController.js
source/Nidan/Nidan/Views/CandidateFee/Detail.cshtml
source/Nidan/Nidan/Views/CandidateFee/Index.cshtml
source/Nidan/Nidan/Views/CandidateFee/_CandidateFee.cshtml

Candidate Edit pending

---

source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan.Data/NidanDataService.cs
source/Nidan/Nidan.Entity/Admission.cs
source/Nidan/Nidan.Entity/CandidateFee.cs
source/Nidan/Nidan/Controllers/AdmissionController.cs
source/Nidan/Nidan/Controllers/RegistrationController.cs
source/Nidan/Nidan/Models/AdmissionViewModel.cs
source/Nidan/Nidan/Views/Admission/Create.cshtml
source/Nidan/Nidan/Views/Admission/_Admission.cshtml
source/Nidan/Nidan/Views/Counselling/Create.cshtml
source/Nidan/Nidan/Views/Counselling/Index.cshtml
source/Nidan/Nidan/Views/Enquiry/Edit.cshtml
source/Nidan/Nidan/Views/Enquiry/Index.cshtml
source/Nidan/Nidan/Views/Registration/Create.cshtml
source/Nidan/Nidan/Views/Registration/Index.cshtml
source/Nidan/Nidan/Views/Registration/_Registration.cshtml

Enquiry to Admission Flow clear with Personnel

Enquiry to Admission Flow clear with Personnel

---

source/Nidan/Nidan.Business/Interfaces/INidanBusinessService.cs
source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan.Data/NidanDataService.cs
source/Nidan/Nidan/Controllers/AdmissionController.cs
source/Nidan/Nidan/Controllers/CounsellingController.cs
source/Nidan/Nidan/Views/Admission/Create.cshtml
source/Nidan/Nidan/Views/Admission/Index.cshtml
source/Nidan/Nidan/Views/Admission/_Admission.cshtml
source/Nidan/Nidan/Views/Counselling/Create.cshtml
source/Nidan/Nidan/Views/Counselling/Index.cshtml
source/Nidan/Nidan/Views/Personnel/Profile.cshtml

Admission Business Change

---

source/Nidan/Nidan.Data/NidanDataService.cs
source/Nidan/Nidan/Controllers/CandidateFeeController.cs
source/Nidan/Nidan/Controllers/RegistrationController.cs
source/Nidan/Nidan/Models/CandidateFeeViewModel.cs
source/Nidan/Nidan/Scripts/Angular/Controllers/CandidateFeeController.js
source/Nidan/Nidan/Scripts/Angular/Services/RegistrationService.js
source/Nidan/Nidan/Views/CandidateFee/Detail.cshtml
source/Nidan/Nidan/Views/CandidateFee/_CandidateFee.cshtml

CandidateFee Payment Detail UI

CandidateFee Payment Detail UI

---

source/Nidan/Nidan.Data/Models/NidanDatabase.cs
source/Nidan/Nidan.Entity/Batch.cs
source/Nidan/Nidan.Entity/Counselling.cs
source/Nidan/Nidan.Entity/Enquiry.cs
source/Nidan/Nidan.Entity/EnquirySearchField.cs
source/Nidan/Nidan.Entity/Partials/Batch.cs
source/Nidan/Nidan.Entity/Partials/Counselling.cs
source/Nidan/Nidan.Entity/Partials/Enquiry.cs
source/Nidan/Nidan.Entity/Partials/Trainer.cs
source/Nidan/Nidan/Controllers/BatchController.cs
source/Nidan/Nidan/Scripts/Angular/Controllers/EnquiryCourseController.js
source/Nidan/Nidan/Views/Batch/Create.cshtml
source/Nidan/Nidan/Views/Batch/Edit.cshtml
source/Nidan/Nidan/Views/Batch/Index.cshtml
source/Nidan/Nidan/Views/Batch/_Batch.cshtml
source/Nidan/Nidan/Views/Counselling/Create.cshtml
source/Nidan/Nidan/Views/Enquiry/Edit.cshtml
source/Nidan/Nidan/Views/Shared/_Counselling.cshtml
source/Nidan/Nidan/Views/Shared/_TrainerDocument.cshtml
source/Nidan/Nidan/Views/Subject/_Subject.cshtml
source/Nidan/Nidan/Views/Trainer/Edit.cshtml
source/Nidan/Nidan/Views/Trainer/Index.cshtml
source/Nidan/Nidan/Views/Trainer/_Trainer.cshtml

Trainer UI and Batch Functionality

Trainer UI and Batch Functionality

---

source/Nidan/Nidan.Entity/Partials/Batch.cs
source/Nidan/Nidan/Views/Batch/Create.cshtml
source/Nidan/Nidan/Views/Batch/Edit.cshtml
source/Nidan/Nidan/Views/Batch/_Batch.cshtml
source/Nidan/Nidan/Views/CourseInstallment/Index.cshtml
source/Nidan/Nidan/Views/Subject/Index.cshtml

Batch Functionality and partial

Batch Functionality and partial

---

source/Nidan/Nidan.Data/NidanDataService.cs
source/Nidan/Nidan/Controllers/HomeController.cs
source/Nidan/Nidan/Models/HomeViewModel.cs
source/Nidan/Nidan/Scripts/Angular/Controllers/HomeController.js
source/Nidan/Nidan/Views/CandidateFee/Detail.cshtml
source/Nidan/Nidan/Views/CandidateFee/Index.cshtml
source/Nidan/Nidan/Views/Home/Index.cshtml

HomeController Index Count and Candidate Fee List Changes

HomeController Index Count and Candidate Fee List Changes

---

source/Nidan/Nidan.Entity/Enquiry.cs
source/Nidan/Nidan/Controllers/EnquiryController.cs
source/Nidan/Nidan/Controllers/HomeController.cs
source/Nidan/Nidan/Scripts/Angular/Controllers/CandidateFeeController.js
source/Nidan/Nidan/Views/Admission/Create.cshtml
source/Nidan/Nidan/Views/Admission/Edit.cshtml
source/Nidan/Nidan/Views/Admission/Index.cshtml
source/Nidan/Nidan/Views/Admission/_Admission.cshtml
source/Nidan/Nidan/Views/CandidateFee/Detail.cshtml
source/Nidan/Nidan/Views/Registration/Edit.cshtml

Candidate Fee, Enquiry And Registrations changes

Candidate Fee, Enquiry And Registrations changes

---

source/Nidan/Nidan/Controllers/CounsellingController.cs
source/Nidan/Nidan/Models/CounsellingViewModel.cs
source/Nidan/Nidan/Views/Counselling/Create.cshtml
source/Nidan/Nidan/Views/Mobilization/Create.cshtml

Counselling Change

---

source/Nidan/Nidan.Business/Models/CandidateFeeReceipt.cs
source/Nidan/Nidan.Business/Nidan.Business.csproj
source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan.Data/NidanDataService.cs
source/Nidan/Nidan/Controllers/CandidateFeeController.cs
source/Nidan/Nidan/Scripts/Angular/Controllers/CandidateFeeController.js
source/Nidan/Nidan/Scripts/Angular/Services/CandidateFeeService.js
source/Nidan/Nidan/Views/CandidateFee/Detail.cshtml
source/Nidan/Nidan/Views/Registration/Edit.cshtml
source/Nidan/Templates/Registration.html

Print Reciept

---

source/Nidan/Nidan.Business/Interfaces/INidanBusinessService.cs
source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan.Entity/Admission.cs
source/Nidan/Nidan/Controllers/AdmissionController.cs
source/Nidan/Nidan/Nidan.csproj
source/Nidan/Nidan/Nidan.csproj.user
source/Nidan/Nidan/Scripts/Angular/Controllers/AdmissionController.js
source/Nidan/Nidan/Views/Admission/AssignBatch.cshtml
source/Nidan/Nidan/Views/Admission/Index.cshtml
source/Nidan/Nidan/Views/Admission/View.cshtml

BatchId Alllow Null In Admission

BatchId Alllow Null In Admission

---

source/Nidan/Nidan.Business/Interfaces/INidanBusinessService.cs
source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan/Controllers/HomeController.cs
source/Nidan/Nidan/Views/Home/Index.cshtml

Pie Changes

---

source/Nidan/Nidan.Business/Interfaces/INidanBusinessService.cs
source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan.Data/Interfaces/INidanDataService.cs
source/Nidan/Nidan.Data/Models/NidanDatabase.cs
source/Nidan/Nidan.Data/NidanDataService.cs
source/Nidan/Nidan.Entity/CandidateInstallmentSearchField.cs
source/Nidan/Nidan.Entity/Nidan.Entity.csproj
source/Nidan/Nidan.Entity/Partials/Subject.cs
source/Nidan/Nidan/Controllers/AdmissionController.cs
source/Nidan/Nidan/Controllers/CandidateFeeController.cs
source/Nidan/Nidan/Controllers/RoomController.cs
source/Nidan/Nidan/Views/Admission/Index.cshtml
source/Nidan/Nidan/Views/CandidateFee/Detail.cshtml
source/Nidan/Nidan/Views/CandidateFee/Index.cshtml
source/Nidan/Nidan/Views/Course/Index.cshtml
source/Nidan/Nidan/Views/CourseInstallment/Index.cshtml
source/Nidan/Nidan/Views/Enquiry/Index.cshtml
source/Nidan/Nidan/Views/FollowUp/Index.cshtml
source/Nidan/Nidan/Views/Mobilization/Index.cshtml
source/Nidan/Nidan/Views/Room/Index.cshtml
source/Nidan/Nidan/Views/Subject/Index.cshtml
source/Nidan/Nidan/Views/Subject/_SessionView.cshtml

CandidateFee Search Pending

---

source/Nidan/Nidan/Views/Admission/Create.cshtml
source/Nidan/Nidan/Views/Admission/Index.cshtml
source/Nidan/Nidan/Views/Registration/Create.cshtml
source/Nidan/Nidan/Views/Registration/Edit.cshtml
source/Nidan/Nidan/Views/Registration/Index.cshtml
source/Nidan/Nidan/Views/Registration/_Registration.cshtml

Registration Edit Sum Of rupees Done

Registration Edit Sum Of rupees Done

---

source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan/Controllers/BatchController.cs
source/Nidan/Nidan/Views/Batch/Create.cshtml
source/Nidan/Nidan/Views/Batch/Edit.cshtml
source/Nidan/Nidan/Views/Batch/_Batch.cshtml

Batch changes

---

source/Nidan/Nidan/Controllers/AdmissionController.cs
source/Nidan/Nidan/Controllers/RegistrationController.cs
source/Nidan/Nidan/Views/Admission/Create.cshtml
source/Nidan/Nidan/Views/Admission/Index.cshtml
source/Nidan/Nidan/Views/Admission/View.cshtml
source/Nidan/Nidan/Views/Registration/Edit.cshtml
source/Nidan/Nidan/Views/Registration/_Registration.cshtml

Admission & Registration Changes

Admission & Registration Changes

---

source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan.Entity/CandidateFee.cs
source/Nidan/Nidan/Controllers/CandidateFeeController.cs
source/Nidan/Nidan/Models/CandidateFeeViewModel.cs
source/Nidan/Nidan/Scripts/Angular/Controllers/CandidateFeeController.js
source/Nidan/Nidan/Views/Admission/Create.cshtml
source/Nidan/Nidan/Views/CandidateFee/Detail.cshtml
source/Nidan/Nidan/Views/CandidateFee/_CandidateFee.cshtml

CandidateFee Changes

---

source/Nidan/Nidan.Business/Nidan.Business.csproj
source/Nidan/Nidan/Scripts/Angular/Controllers/CandidateFeeController.js
source/Nidan/Nidan/Views/CandidateFee/Detail.cshtml
source/Nidan/Nidan/Views/CandidateFee/_CandidateFee.cshtml

Candidate Fee pop up

---

source/Nidan/Nidan.Business/Interfaces/INidanBusinessService.cs
source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan.Data/NidanDataService.cs
source/Nidan/Nidan/Controllers/OtherFeeController.cs
source/Nidan/Nidan/Controllers/OtherFeeProjectController.cs
source/Nidan/Nidan/Scripts/Angular/Controllers/OtherFeeProjectController.js
source/Nidan/Nidan/Scripts/Angular/Controllers/ProjectController.js
source/Nidan/Nidan/Scripts/Angular/Services/OtherFeeProjectService.js
source/Nidan/Nidan/Scripts/Angular/Services/ProjectService.js
source/Nidan/Nidan/Views/OtherFee/Create.cshtml
source/Nidan/Nidan/Views/OtherFee/Edit.cshtml
source/Nidan/Nidan/Views/OtherFee/_OtherFee.cshtml

Other Fee Changes

---

source/Nidan/Nidan.Business/Nidan.Business.csproj
source/Nidan/Nidan.Data/NidanDataService.cs
source/Nidan/Nidan.Entity/FollowUpDataGrid.cs
source/Nidan/Nidan/Controllers/ReportController.cs
source/Nidan/Nidan/Scripts/Angular/Controllers/ReportController.js
source/Nidan/Nidan/Views/Report/Enquiry.cshtml
source/Nidan/Nidan/Views/Report/FollowUp.cshtml
source/Nidan/Nidan/Views/Report/Mobilization.cshtml

Paging and FollowUp Grid changes

Paging and FollowUp Grid changes

---

source/Nidan/Nidan/Controllers/DocumentController.cs
source/Nidan/Nidan/Nidan.csproj
source/Nidan/Nidan/Scripts/Angular/Controllers/OtherFeeController.js
source/Nidan/Nidan/Views/Admission/Create.cshtml
source/Nidan/Nidan/Views/Admission/View.cshtml
source/Nidan/Nidan/Views/Admission/_AdmissionDocument.cshtml
source/Nidan/Nidan/Views/OtherFee/Create.cshtml
source/Nidan/Nidan/Views/OtherFee/Index.cshtml
source/Nidan/Nidan/Views/OtherFee/_Expenses.cshtml

Admission And OtherFee Document Upload Completed

Admission And OtherFee Document Upload Completed

---

source/Nidan/Nidan.Data/NidanDataService.cs
source/Nidan/Nidan/Controllers/PersonnelController.cs
source/Nidan/Nidan/Scripts/Angular/Controllers/PersonnelProfileController.js
source/Nidan/Nidan/Scripts/Angular/Services/PersonnelProfileService.js
source/Nidan/Nidan/Views/Personnel/Profile.cshtml

Personnel Profile Changes

---

source/Nidan/Nidan.Business/Nidan.Business.csproj
source/Nidan/Nidan/Controllers/ReportController.cs
source/Nidan/Nidan/Nidan.csproj
source/Nidan/Nidan/Scripts/Angular/Controllers/ReportController.js
source/Nidan/Nidan/Scripts/Angular/Services/ReportService.js
source/Nidan/Nidan/Views/Report/Admission.cshtml
source/Nidan/Nidan/Views/Shared/_Layout.cshtml

Admission Grid For Reports

---

source/Nidan/Nidan.Business/Interfaces/INidanBusinessService.cs
source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan.Data/Interfaces/INidanDataService.cs
source/Nidan/Nidan.Data/Models/NidanDatabase.cs
source/Nidan/Nidan.Data/NidanDataService.cs
source/Nidan/Nidan.Entity/Attendance.cs
source/Nidan/Nidan.Entity/Batch.cs
source/Nidan/Nidan.Entity/BatchAttendance.cs
source/Nidan/Nidan.Entity/BatchTrainer.cs
source/Nidan/Nidan.Entity/Centre.cs
source/Nidan/Nidan.Entity/Nidan.Entity.csproj
source/Nidan/Nidan.Entity/Organisation.cs
source/Nidan/Nidan.Entity/Personnel.cs
source/Nidan/Nidan.Entity/Session.cs
source/Nidan/Nidan.Entity/Subject.cs
source/Nidan/Nidan/Controllers/AttendanceController.cs
source/Nidan/Nidan/Models/AttendanceViewModel.cs
source/Nidan/Nidan/Nidan.csproj
source/Nidan/Nidan/Scripts/Angular/Controllers/AttendanceController.js
source/Nidan/Nidan/Scripts/Angular/Services/AttendanceService.js
source/Nidan/Nidan/Views/Attendance/Create.cshtml
source/Nidan/Nidan/Views/Attendance/Index.cshtml
source/Nidan/Nidan/Views/Attendance/_Attendance.cshtml
source/Nidan/Nidan/Views/Report/Enquiry.cshtml
source/Nidan/Nidan/Views/Report/FollowUp.cshtml
source/Nidan/Nidan/Views/Report/Mobilization.cshtml
source/Nidan/Nidan/Views/Shared/_Layout.cshtml

Attendance

---

source/Nidan/Nidan.Business/Interfaces/INidanBusinessService.cs
source/Nidan/Nidan.Business/Models/OtherFeeReceipt.cs
source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan.Data/NidanDataService.cs
source/Nidan/Nidan.Entity/Expense.cs
source/Nidan/Nidan/Controllers/OtherFeeController.cs
source/Nidan/Nidan/Scripts/Angular/Controllers/OtherFeeController.js
source/Nidan/Nidan/Views/OtherFee/Create.cshtml
source/Nidan/Nidan/Views/OtherFee/Edit.cshtml
source/Nidan/Nidan/Views/OtherFee/Index.cshtml
source/Nidan/Nidan/Views/OtherFee/_OtherFee.cshtml
source/Nidan/Nidan/Views/OtherFee/_OtherFeeDocument.cshtml
source/Nidan/Templates/OtherFee.html

petty cash re-edited Receipt.

---

source/Nidan/Nidan/Controllers/BatchAttendanceController.cs
source/Nidan/Nidan/Models/BatchAttendanceViewModel.cs
source/Nidan/Nidan/Nidan.csproj
source/Nidan/Nidan/Scripts/Angular/Controllers/BatchAttendanceController.js
source/Nidan/Nidan/Views/BatchAttendance/Create.cshtml
source/Nidan/Nidan/Views/BatchAttendance/_Attendance.cshtml
source/Nidan/Nidan/Views/BatchAttendance/_AttendanceDataGrid.cshtml

Attendance List and Batch Attendance UI

Attendance List and Batch Attendance UI

---

source/Nidan/Nidan/Controllers/BatchAttendanceController.cs
source/Nidan/Nidan/Scripts/Angular/Controllers/BatchAttendanceController.js
source/Nidan/Nidan/Scripts/Angular/Controllers/BatchController.js
source/Nidan/Nidan/Scripts/Angular/Services/BatchService.js
source/Nidan/Nidan/Views/BatchAttendance/_Attendance.cshtml

Batch Attendance

---

source/Nidan/Nidan/Controllers/BatchAttendanceController.cs
source/Nidan/Nidan/Scripts/Angular/Controllers/BatchAttendanceController.js
source/Nidan/Nidan/Scripts/Angular/Services/BatchAttendanceService.js
source/Nidan/Nidan/Views/BatchAttendance/Index.cshtml
source/Nidan/Nidan/Views/BatchAttendance/_Attendance.cshtml

Batch DropdownList using angular completed

Batch DropdownList using angular completed

---

source/Nidan/Nidan.Business/Helper/CsvHelper.cs
source/Nidan/Nidan/Controllers/ReportController.cs
source/Nidan/Nidan/Scripts/Angular/Controllers/ReportController.js
source/Nidan/Nidan/Scripts/Angular/Services/ReportService.js
source/Nidan/Nidan/Views/Report/Admission.cshtml
source/Nidan/Nidan/Views/Report/Counselling.cshtml
source/Nidan/Nidan/Views/Report/Enquiry.cshtml
source/Nidan/Nidan/Views/Report/Expense.cshtml
source/Nidan/Nidan/Views/Report/FollowUp.cshtml
source/Nidan/Nidan/Views/Report/Mobilization.cshtml
source/Nidan/Nidan/Views/Report/Registration.cshtml

Download CSV

---

source/Nidan/Nidan.Business/Interfaces/INidanBusinessService.cs
source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan.Data/Interfaces/INidanDataService.cs
source/Nidan/Nidan.Data/Models/NidanDatabase.cs
source/Nidan/Nidan.Data/NidanDataService.cs
source/Nidan/Nidan.Entity/MobilizationDataGrid.cs
source/Nidan/Nidan/Controllers/MobilizationController.cs
source/Nidan/Nidan/Scripts/Angular/Controllers/MobilizationController.js
source/Nidan/Nidan/Scripts/Angular/Controllers/ReportController.js
source/Nidan/Nidan/Views/Mobilization/Index.cshtml
source/Nidan/Nidan/Views/Registration/Index.cshtml
source/Nidan/Nidan/Views/Report/Admission.cshtml
source/Nidan/Nidan/Views/Report/Counselling.cshtml
source/Nidan/Nidan/Views/Report/Enquiry.cshtml
source/Nidan/Nidan/Views/Report/FollowUp.cshtml
source/Nidan/Nidan/Views/Report/Mobilization.cshtml
source/Nidan/Nidan/Views/Report/Registration.cshtml

Report and Mobilization Search completed

Report and Mobilization Search completed

---

source/Nidan/Nidan.Data/NidanDataService.cs
source/Nidan/Nidan/Views/Shared/_Layout.cshtml

Minor Change

---

source/Nidan/Nidan.Business/Interfaces/INidanBusinessService.cs
source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan.Data/NidanDataService.cs
source/Nidan/Nidan/Controllers/CentreController.cs
source/Nidan/Nidan/Controllers/ReportController.cs
source/Nidan/Nidan/Views/Shared/_Layout.cshtml

Changes on 11th july 2017

---

source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan/Controllers/BatchAttendanceController.cs
source/Nidan/Nidan/Controllers/HomeController.cs
source/Nidan/Nidan/Controllers/RegistrationController.cs
source/Nidan/Nidan/Views/CandidateFee/Detail.cshtml
source/Nidan/Nidan/Views/Mobilization/_Mobilization.cshtml
source/Nidan/Nidan/Views/Shared/_Layout.cshtml

Minor Bug Fixes in Home,Registration,Attendance,CandidateFee

Minor Bug Fixes in Home,Registration,Attendance,CandidateFee

---

source/Nidan/Nidan/Controllers/BatchAttendanceController.cs
source/Nidan/Nidan/Models/BatchAttendanceViewModel.cs
source/Nidan/Nidan/Scripts/Angular/Controllers/BatchAttendanceController.js.orig
source/Nidan/Nidan/Scripts/Angular/Services/BatchAttendanceService.js.orig
source/Nidan/Nidan/Views/BatchAttendance/_AttendanceDataGrid.cshtml
source/Nidan/Nidan/Views/BatchAttendance/_AttendanceDataGrid.cshtml.orig
source/Nidan/Nidan/Views/Shared/_Layout.cshtml.orig

AattendanceList

---

source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan/Controllers/AdmissionController.cs
source/Nidan/Nidan/Controllers/RegistrationController.cs
source/Nidan/Nidan/Controllers/ReportController.cs
source/Nidan/Nidan/Scripts/Angular/Controllers/RegistrationController.js
source/Nidan/Nidan/Scripts/Angular/Services/RegistrationService.js
source/Nidan/Nidan/Views/Admission/Index.cshtml
source/Nidan/Nidan/Views/Attendance/Index.cshtml
source/Nidan/Nidan/Views/Batch/Index.cshtml
source/Nidan/Nidan/Views/Counselling/Index.cshtml
source/Nidan/Nidan/Views/Enquiry/Index.cshtml
source/Nidan/Nidan/Views/FollowUp/Index.cshtml
source/Nidan/Nidan/Views/Mobilization/Index.cshtml
source/Nidan/Nidan/Views/Registration/Index.cshtml
source/Nidan/Nidan/Views/Report/Admission.cshtml
source/Nidan/Nidan/Views/Report/Counselling.cshtml
source/Nidan/Nidan/Views/Report/Enquiry.cshtml
source/Nidan/Nidan/Views/Report/FollowUp.cshtml
source/Nidan/Nidan/Views/Report/Mobilization.cshtml
source/Nidan/Nidan/Views/Report/Registration.cshtml
source/Nidan/Nidan/Views/Shared/_Layout.cshtml
source/Nidan/Nidan/Views/Shared/_OutsideLayout.cshtml

Admission Email and Registration Search and replace leaf to Nidan N

Admission Email and Registration Search and replace leaf to Nidan N

---

source/Nidan/Nidan.Data/NidanDataService.cs
source/Nidan/Nidan/Controllers/BatchController.cs
source/Nidan/Nidan/Controllers/TrainerController.cs
source/Nidan/Nidan/Nidan.csproj
source/Nidan/Nidan/Scripts/Angular/Controllers/BatchController.js
source/Nidan/Nidan/Scripts/Angular/Controllers/CounsellingController.js
source/Nidan/Nidan/Scripts/Angular/Controllers/EnquiryController.js
source/Nidan/Nidan/Scripts/Angular/Controllers/TrainerController.js
source/Nidan/Nidan/Views/Admission/Index.cshtml
source/Nidan/Nidan/Views/Admission/View.cshtml
source/Nidan/Nidan/Views/Batch/Index.cshtml
source/Nidan/Nidan/Views/Batch/View.cshtml
source/Nidan/Nidan/Views/Enquiry/_Enquiry.cshtml
source/Nidan/Nidan/Views/Shared/_Layout.cshtml
source/Nidan/Nidan/Views/Trainer/Index.cshtml
source/Nidan/Nidan/Views/Trainer/View.cshtml

Batch View, Trainer View & DB Script

Batch View, Trainer View & DB Script

---

source/Nidan/Nidan.Data/Models/NidanDatabase.cs
source/Nidan/Nidan.Entity/AttendanceGrid.cs
source/Nidan/Nidan/Controllers/BatchAttendanceController.cs
source/Nidan/Nidan/Scripts/Angular/Controllers/BatchAttendanceController.js
source/Nidan/Nidan/Scripts/Angular/Services/BatchAttendanceService.js
source/Nidan/Nidan/Views/BatchAttendance/Index.cshtml

Batch Attendance List

---

source/Nidan/Nidan.Business/Interfaces/INidanBusinessService.cs
source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan.Data/Interfaces/INidanDataService.cs
source/Nidan/Nidan.Data/Models/NidanDatabase.cs
source/Nidan/Nidan.Data/NidanDataService.cs
source/Nidan/Nidan.Entity/Brainstorming.cs
source/Nidan/Nidan.Entity/Centre.cs
source/Nidan/Nidan.Entity/Event.cs
source/Nidan/Nidan.Entity/EventBrainstorming.cs
source/Nidan/Nidan.Entity/Nidan.Entity.csproj
source/Nidan/Nidan.Entity/Organisation.cs
source/Nidan/Nidan/Controllers/BatchAttendanceController.cs
source/Nidan/Nidan/Controllers/EventController.cs
source/Nidan/Nidan/Models/EventViewModel.cs
source/Nidan/Nidan/Scripts/Angular/Controllers/BrainstormingController.js
source/Nidan/Nidan/Scripts/Angular/Services/BrainstormingService.js
source/Nidan/Nidan/Views/Admission/Create.cshtml
source/Nidan/Nidan/Views/Admission/Edit.cshtml
source/Nidan/Nidan/Views/Event/_BrainStorming.cshtml
source/Nidan/Nidan/Views/Registration/Create.cshtml
source/Nidan/Nidan/Views/Registration/Edit.cshtml
source/Nidan/Nidan/Views/Shared/_Layout.cshtml

Event Brainstorming UI and code

Event Brainstorming UI and code

---

source/Nidan/Nidan.Business/Interfaces/INidanBusinessService.cs
source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan.Data/Interfaces/INidanDataService.cs
source/Nidan/Nidan.Data/Models/NidanDatabase.cs
source/Nidan/Nidan.Data/NidanDataService.cs
source/Nidan/Nidan.Entity/Budget.cs
source/Nidan/Nidan.Entity/Centre.cs
source/Nidan/Nidan.Entity/Event.cs
source/Nidan/Nidan.Entity/EventBudget.cs
source/Nidan/Nidan.Entity/EventPlanning.cs
source/Nidan/Nidan.Entity/EventPostEvent.cs
source/Nidan/Nidan.Entity/Nidan.Entity.csproj
source/Nidan/Nidan.Entity/Organisation.cs
source/Nidan/Nidan.Entity/Planning.cs
source/Nidan/Nidan.Entity/Postevent.cs
source/Nidan/Nidan.Entity/Question.cs
source/Nidan/Nidan/Controllers/EventController.cs
source/Nidan/Nidan/Views/Event/Create.cshtml
source/Nidan/Nidan/Views/Event/Edit.cshtml
source/Nidan/Nidan/Views/Event/_BrainStorming.cshtml
source/Nidan/Templates/Enrollment.html
source/Nidan/Templates/Installment.html
source/Nidan/Templates/Registration.html

Event BASE

---

source/Nidan/Nidan.Business/Interfaces/INidanBusinessService.cs
source/Nidan/Nidan.Business/Nidan.Business.csproj
source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan.Data/Interfaces/INidanDataService.cs
source/Nidan/Nidan.Data/Models/NidanDatabase.cs
source/Nidan/Nidan.Data/NidanDataService.cs
source/Nidan/Nidan.Entity/BiometricAttendanceGrid.cs
source/Nidan/Nidan.Entity/Nidan.Entity.csproj
source/Nidan/Nidan/Controllers/BatchAttendanceController.cs
source/Nidan/Nidan/Scripts/Angular/Controllers/BatchAttendanceController.js
source/Nidan/Nidan/Scripts/Angular/Services/BatchAttendanceService.js
source/Nidan/Nidan/Views/BatchAttendance/_Attendance.cshtml
source/Nidan/Nidan/Views/BatchAttendance/_AttendanceDataGrid.cshtml
source/Nidan/Nidan/Views/Counselling/Create.cshtml

Attendance SYNC

---

source/Nidan/Nidan.Business/Interfaces/INidanBusinessService.cs
source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan.Data/Interfaces/INidanDataService.cs
source/Nidan/Nidan.Data/Models/NidanDatabase.cs
source/Nidan/Nidan.Data/NidanDataService.cs
source/Nidan/Nidan.Entity/EventBrainStormingGrid.cs
source/Nidan/Nidan.Entity/Nidan.Entity.csproj
source/Nidan/Nidan/Controllers/EnquiryController.cs
source/Nidan/Nidan/Controllers/EventController.cs
source/Nidan/Nidan/Scripts/Angular/Controllers/BrainstormingController.js
source/Nidan/Nidan/Scripts/Angular/Controllers/CourseController.js
source/Nidan/Nidan/Scripts/Angular/Services/BrainstormingService.js
source/Nidan/Nidan/Views/Enquiry/Create.cshtml
source/Nidan/Nidan/Views/Event/Edit.cshtml
source/Nidan/Nidan/Views/Event/_BrainStorming.cshtml

Eneuiry Bug Solve & Event In Progress

Eneuiry Bug Solve & Event In Progress

---

source/Nidan/Nidan.Business/Interfaces/INidanBusinessService.cs
source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan.Data/Models/NidanDatabase.cs
source/Nidan/Nidan.Entity/BatchPlanner.cs
source/Nidan/Nidan.Entity/Course.cs
source/Nidan/Nidan.Entity/CourseSearchField.cs
source/Nidan/Nidan.Entity/CourseType.cs
source/Nidan/Nidan.Entity/Partials/Course.cs
source/Nidan/Nidan/Controllers/BatchPlannerController.cs
source/Nidan/Nidan/Controllers/HomeController.cs
source/Nidan/Nidan/Views/BatchPlanner/Create.cshtml
source/Nidan/Nidan/Views/BatchPlanner/_BatchPlanner.cshtml
source/Nidan/Nidan/Views/Course/Create.cshtml
source/Nidan/Nidan/Views/Course/_Course.cshtml

Bug Solve (Enquiry count & MobilizationCentreReport)

Bug Solve (Enquiry count & MobilizationCentreReport)

---

source/Nidan/Nidan/Scripts/Angular/Controllers/AdmissionController.js
source/Nidan/Nidan/Scripts/Angular/Controllers/AttendanceController.js
source/Nidan/Nidan/Scripts/Angular/Controllers/BatchController.js
source/Nidan/Nidan/Scripts/Angular/Controllers/CandidateFeeController.js
source/Nidan/Nidan/Scripts/Angular/Controllers/CounsellingController.js
source/Nidan/Nidan/Scripts/Angular/Controllers/EnquiryController.js
source/Nidan/Nidan/Scripts/Angular/Controllers/FollowUpController.js
source/Nidan/Nidan/Scripts/Angular/Controllers/RegistrationController.js
source/Nidan/Nidan/Views/BatchPlanner/Create.cshtml

BatchController Changes & Search By Date Bug Solved

BatchController Changes & Search By Date Bug Solved

---

source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan.Entity/CandidateInstallment.cs
source/Nidan/Nidan/Controllers/ExpenseController.cs
source/Nidan/Nidan/Controllers/HomeController.cs
source/Nidan/Nidan/Controllers/StockPurchaseController.cs
source/Nidan/Nidan/Views/Home/Index.cshtml

DateTime.Utc.Now Refactor

---

source/Nidan/Nidan/Views/BatchPlanner/Create.cshtml
source/Nidan/Nidan/Views/BatchPlanner/_BatchPlanner.cshtml

BatchPlanner Changes

---

source/Nidan/Nidan.Business/Interfaces/INidanBusinessService.cs
source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan.Data/Models/NidanDatabase.cs
source/Nidan/Nidan.Entity/Nidan.Entity.csproj
source/Nidan/Nidan.Entity/StockPurchase.cs
source/Nidan/Nidan.Entity/StudentKit.cs
source/Nidan/Nidan/Controllers/StockPurchaseController.cs
source/Nidan/Nidan/Models/StockPurchaseViewModel.cs
source/Nidan/Nidan/Views/StockPurchase/Create.cshtml
source/Nidan/Nidan/Views/StockPurchase/_StockPurchase.cshtml

Stock Changes

---

source/Nidan/Nidan/Views/Expense/Create.cshtml
source/Nidan/Nidan/Views/Expense/Index.cshtml
source/Nidan/Nidan/Views/Shared/_Layout.cshtml

Small change in Petty Cash

---

source/Nidan/Nidan/Views/Account/ResetPassword.cshtml

Reset pssword note added

---

source/Nidan/Nidan/Scripts/Angular/Controllers/ExpenseController.js
source/Nidan/Nidan/Views/Expense/Create.cshtml
source/Nidan/Nidan/Views/Expense/Edit.cshtml
source/Nidan/Nidan/Views/Expense/_Expense.cshtml

Petty Cash Dropdown Bug Fix

---

source/Nidan/Nidan.Entity/Expense.cs
source/Nidan/Nidan/Controllers/ExpenseController.cs
source/Nidan/Nidan/Nidan.csproj
source/Nidan/Nidan/Views/Admission/Create.cshtml
source/Nidan/Nidan/Views/Counselling/Create.cshtml
source/Nidan/Nidan/Views/Expense/Edit.cshtml
source/Nidan/Nidan/Views/Expense/Index.cshtml
source/Nidan/Nidan/Views/Expense/TermsAndCondition.cshtml
source/Nidan/Nidan/Views/Expense/_Expense.cshtml
source/Nidan/Nidan/Views/Shared/_Layout.cshtml
source/Nidan/Templates/CandidateFeeEnrollment.html
source/Nidan/Templates/Enrollment.html
source/Nidan/Templates/FeeTermsAndConditions.html
source/Nidan/Templates/Installment.html
source/Nidan/Templates/OtherFee.html
source/Nidan/Templates/Registration.html

Petty Cash Changes & Template Changes

Petty Cash Changes & Template Changes

---

source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan/Views/Admission/Create.cshtml
source/Nidan/Nidan/Views/Admission/_Admission.cshtml
source/Nidan/Nidan/Views/Trainer/Index.cshtml

Admission Override Fee

---

source/Nidan/Nidan.Business/Interfaces/INidanBusinessService.cs
source/Nidan/Nidan.Business/Models/AvailablePettyCashReport.cs
source/Nidan/Nidan.Business/Nidan.Business.csproj
source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan.Data/Interfaces/INidanDataService.cs
source/Nidan/Nidan.Data/Models/NidanDatabase.cs
source/Nidan/Nidan.Data/NidanDataService.cs
source/Nidan/Nidan.Entity/AvailablePettyCashGrid.cs
source/Nidan/Nidan.Entity/Nidan.Entity.csproj
source/Nidan/Nidan/Controllers/ReportController.cs
source/Nidan/Nidan/Nidan.csproj
source/Nidan/Nidan/Scripts/Angular/Controllers/ReportController.js
source/Nidan/Nidan/Scripts/Angular/Services/ReportService.js
source/Nidan/Nidan/Views/Report/CentrePettyCashByCentre.cshtml
source/Nidan/Nidan/Views/Report/Expense.cshtml
source/Nidan/Nidan/Views/Shared/_Layout.cshtml

available petty cash report

---

source/Nidan/Nidan.Business/Interfaces/INidanBusinessService.cs
source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan.Data/Interfaces/INidanDataService.cs
source/Nidan/Nidan.Data/Models/NidanDatabase.cs
source/Nidan/Nidan.Data/NidanDataService.cs
source/Nidan/Nidan.Entity/ExpenseHeadLimit.cs
source/Nidan/Nidan.Entity/Nidan.Entity.csproj
source/Nidan/Nidan/Controllers/ExpenseController.cs
source/Nidan/Nidan/Scripts/Angular/Controllers/ExpenseController.js
source/Nidan/Nidan/Views/Expense/Create.cshtml
source/Nidan/Nidan/Views/Expense/Edit.cshtml

Petty Cash Changes.

---

source/Nidan/Nidan/Controllers/ExpenseController.cs
source/Nidan/Nidan/Scripts/Angular/Controllers/ExpenseController.js
source/Nidan/Nidan/Scripts/Angular/Services/ExpenseService.js
source/Nidan/Nidan/Views/Expense/Index.cshtml

Centre Dropdown in Expense Index

Centre Dropdown in Expense Index

---

source/Nidan/Nidan/Controllers/ExpenseController.cs
source/Nidan/Nidan/Scripts/Angular/Controllers/ExpenseController.js
source/Nidan/Nidan/Scripts/Angular/Services/ExpenseService.js
source/Nidan/Nidan/Views/CandidateFee/Detail.cshtml
source/Nidan/Nidan/Views/Expense/Index.cshtml

Petty cash changes

---

source/Nidan/Nidan.Business/Interfaces/INidanBusinessService.cs
source/Nidan/Nidan.Business/Models/AvailablePettyCashReport.cs
source/Nidan/Nidan.Business/Nidan.Business.csproj
source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan.Data/Interfaces/INidanDataService.cs
source/Nidan/Nidan.Data/Models/NidanDatabase.cs
source/Nidan/Nidan.Data/NidanDataService.cs
source/Nidan/Nidan.Entity/AvailablePettyCashGrid.cs
source/Nidan/Nidan.Entity/Nidan.Entity.csproj
source/Nidan/Nidan/Controllers/CentrePettyCashController.cs
source/Nidan/Nidan/Controllers/ReportController.cs
source/Nidan/Nidan/Nidan.csproj
source/Nidan/Nidan/Scripts/Angular/Controllers/CentrePettyCashController.js
source/Nidan/Nidan/Scripts/Angular/Controllers/ReportController.js
source/Nidan/Nidan/Scripts/Angular/Services/CentrePettyCashService.js
source/Nidan/Nidan/Scripts/Angular/Services/ReportService.js
source/Nidan/Nidan/Views/CentrePettyCash/Index.cshtml
source/Nidan/Nidan/Views/Report/CentrePettyCashByCentre.cshtml
source/Nidan/Nidan/Views/Report/Expense.cshtml
source/Nidan/Nidan/Views/Shared/_Layout.cshtml

AvailablePettyCash and CentrePettyCashByCentre Changes

AvailablePettyCash and CentrePettyCashByCentre Changes

---

source/Nidan/Nidan.Business/Interfaces/INidanBusinessService.cs
source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan.Data/Interfaces/INidanDataService.cs
source/Nidan/Nidan.Data/Models/NidanDatabase.cs
source/Nidan/Nidan.Data/NidanDataService.cs
source/Nidan/Nidan.Entity/Expense.cs
source/Nidan/Nidan.Entity/ExpenseHeadLimit.cs
source/Nidan/Nidan.Entity/Nidan.Entity.csproj
source/Nidan/Nidan/Controllers/ExpenseController.cs
source/Nidan/Nidan/Nidan.csproj
source/Nidan/Nidan/Scripts/Angular/Controllers/ExpenseController.js
source/Nidan/Nidan/Scripts/Angular/Services/ExpenseService.js
source/Nidan/Nidan/Views/Expense/Create.cshtml
source/Nidan/Nidan/Views/Expense/Edit.cshtml
source/Nidan/Nidan/Views/Expense/Index.cshtml
source/Nidan/Nidan/Views/Expense/TermsAndCondition.cshtml
source/Nidan/Nidan/Views/Expense/_Expense.cshtml
source/Nidan/Nidan/Views/Expense/_ExpenseDocument.cshtml
source/Nidan/Nidan/Views/Shared/_Layout.cshtml

Petty Cash ExpenseHeadLimit

---

source/Nidan/Nidan.Business/Interfaces/INidanBusinessService.cs
source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan.Data/Interfaces/INidanDataService.cs
source/Nidan/Nidan.Data/NidanDataService.cs
source/Nidan/Nidan.Entity/BankDeposite.cs
source/Nidan/Nidan.Entity/BankDepositeSearchField.cs
source/Nidan/Nidan/Controllers/BankDepositeController.cs
source/Nidan/Nidan/Controllers/ExpenseController.cs
source/Nidan/Nidan/Scripts/Angular/Controllers/BankDepositeController.js
source/Nidan/Nidan/Scripts/Angular/Controllers/ExpenseController.js
source/Nidan/Nidan/Scripts/Angular/Services/BankDepositeService.js
source/Nidan/Nidan/Scripts/Angular/Services/ExpenseService.js
source/Nidan/Nidan/Views/BankDeposite/Index.cshtml
source/Nidan/Nidan/Views/BankDeposite/_BankDeposite.cshtml
source/Nidan/Nidan/Views/Expense/Create.cshtml
source/Nidan/Nidan/Views/Expense/Index.cshtml
source/Nidan/Nidan/Views/Expense/_Expense.cshtml

Bank Deposit and Expense Changes

Bank Deposit and Expense Changes

---

source/Nidan/Nidan/Controllers/ActivityTaskController.cs
source/Nidan/Nidan/Models/ActivityTaskViewModel.cs
source/Nidan/Nidan/Views/ActivityTask/Create.cshtml

ActivityTask Changes

---

source/Nidan/Nidan.Business/Interfaces/INidanBusinessService.cs
source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan.Data/Interfaces/INidanDataService.cs
source/Nidan/Nidan.Data/Models/NidanDatabase.cs
source/Nidan/Nidan.Data/NidanDataService.cs
source/Nidan/Nidan.Entity/Centre.cs
source/Nidan/Nidan.Entity/District.cs
source/Nidan/Nidan.Entity/Nidan.Entity.csproj
source/Nidan/Nidan.Entity/Organisation.cs
source/Nidan/Nidan.Entity/Partner.cs
source/Nidan/Nidan.Entity/State.cs
source/Nidan/Nidan.Entity/Taluka.cs
source/Nidan/Nidan/Controllers/CentreController.cs
source/Nidan/Nidan/Controllers/PartnerController.cs
source/Nidan/Nidan/Models/PartnerViewModel.cs
source/Nidan/Nidan/Nidan.csproj
source/Nidan/Nidan/Views/Centre/Create.cshtml
source/Nidan/Nidan/Views/CentrePettyCash/Create.cshtml
source/Nidan/Nidan/Views/Expense/_Expense.cshtml

Partner Management

---

source/Nidan/Nidan.Business/Interfaces/INidanBusinessService.cs
source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan.Data/Models/NidanDatabase.cs
source/Nidan/Nidan.Entity/CandidateAssessmentQuestionAnswer.cs
source/Nidan/Nidan.Entity/ModuleExamQuestionAnswerGrid.cs
source/Nidan/Nidan/Controllers/AssessmentController.cs
source/Nidan/Nidan/Controllers/CandidateAssessmentQuestionAnswerController.cs
source/Nidan/Nidan/Nidan.csproj
source/Nidan/Nidan/Scripts/Angular/Controllers/AssesmentController.js
source/Nidan/Nidan/Scripts/Angular/Services/AssesmentService.js
source/Nidan/Nidan/Views/Assessment/AssessmentByUser.cshtml
source/Nidan/Nidan/Views/CandidateAssessmentQuestionAnswer/CandidateAssessmentQuestionAnswer.cshtml
source/Nidan/Nidan/Views/Home/Index.cshtml

Assessment Changes

---

source/Nidan/Nidan.Business/Interfaces/INidanBusinessService.cs
source/Nidan/Nidan/Controllers/CandidateAssessmentQuestionAnswerController.cs
source/Nidan/Nidan/Scripts/Angular/Controllers/AssesmentController.js
source/Nidan/Nidan/Views/CandidateAssessmentQuestionAnswer/CandidateAssessmentQuestionAnswer.cshtml

CandidateAssessmentQuestionAnswer Angular Changes

CandidateAssessmentQuestionAnswer Angular Changes

---

source/Nidan/Nidan.Entity/Centre.cs
source/Nidan/Nidan.Entity/Partials/Centre.cs
source/Nidan/Nidan/Controllers/CandidateFeeController.cs
source/Nidan/Nidan/Controllers/CentreController.cs
source/Nidan/Nidan/Controllers/PartnerController.cs
source/Nidan/Nidan/Nidan.csproj
source/Nidan/Nidan/Scripts/Angular/Controllers/PartnerController.js
source/Nidan/Nidan/Scripts/Angular/Services/PartnerService.js
source/Nidan/Nidan/Views/Centre/Create.cshtml
source/Nidan/Nidan/Views/Centre/Edit.cshtml
source/Nidan/Nidan/Views/Centre/Index.cshtml
source/Nidan/Nidan/Views/Enquiry/View.cshtml
source/Nidan/Nidan/Views/Partner/Create.cshtml
source/Nidan/Nidan/Views/Partner/Edit.cshtml
source/Nidan/Nidan/Views/Partner/Index.cshtml
source/Nidan/Nidan/Views/Shared/_Layout.cshtml
source/Nidan/Nidan/Views/Trainer/Edit.cshtml

Centre Changes & Partner CRUD

---

source/Nidan/Nidan.Business/Interfaces/INidanBusinessService.cs
source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan.Data/Interfaces/INidanDataService.cs
source/Nidan/Nidan.Data/NidanDataService.cs
source/Nidan/Nidan/Controllers/AssessmentController.cs
source/Nidan/Nidan/Controllers/CandidateAssessmentQuestionAnswerController.cs
source/Nidan/Nidan/Controllers/SubjectController.cs
source/Nidan/Nidan/Models/CandidateAssessmentQuestionAnswerViewModel.cs
source/Nidan/Nidan/Nidan.csproj
source/Nidan/Nidan/Nidan.csproj.user
source/Nidan/Nidan/Scripts/Angular/Controllers/AssesmentController.js
source/Nidan/Nidan/Scripts/Angular/Services/AssesmentService.js
source/Nidan/Nidan/Views/Assessment/AssessmentByTrainer.cshtml
source/Nidan/Nidan/Views/CandidateAssessmentQuestionAnswer/CandidateAssessmentDetail.cshtml
source/Nidan/Nidan/Views/Enquiry/View.cshtml
source/Nidan/Nidan/Views/Home/Index.cshtml
source/Nidan/Nidan/Views/Shared/_Layout.cshtml

Session Planner and Trainer Assesment list Completed

Session Planner and Trainer Assesment list Completed

---

source/Nidan/Nidan.Business/Enum/TaskState.cs
source/Nidan/Nidan.Business/Interfaces/INidanBusinessService.cs
source/Nidan/Nidan.Business/Nidan.Business.csproj
source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan.Data/Interfaces/INidanDataService.cs
source/Nidan/Nidan.Data/Models/NidanDatabase.cs
source/Nidan/Nidan.Data/NidanDataService.cs
source/Nidan/Nidan.Entity/Activity.cs
source/Nidan/Nidan.Entity/ActivityDataGrid.cs
source/Nidan/Nidan.Entity/ActivityTaskDataGrid.cs
source/Nidan/Nidan.Entity/EventManagementGrid.cs
source/Nidan/Nidan.Entity/Nidan.Entity.csproj
source/Nidan/Nidan.Entity/Partials/Activity.cs
source/Nidan/Nidan.Entity/TaskState.cs
source/Nidan/Nidan/Controllers/ActivityController.cs
source/Nidan/Nidan/Controllers/ActivityTaskController.cs
source/Nidan/Nidan/Controllers/EventController.cs
source/Nidan/Nidan/Models/ActivityViewModel.cs
source/Nidan/Nidan/Views/Activity/Edit.cshtml
source/Nidan/Nidan/Views/Activity/Index.cshtml
source/Nidan/Nidan/Views/ActivityTask/Create.cshtml
source/Nidan/Nidan/Views/ActivityTask/Edit.cshtml
source/Nidan/Nidan/Views/ActivityTask/Index.cshtml
source/Nidan/Nidan/Views/ActivityTask/_ActivityTask.cshtml
source/Nidan/Nidan/Views/ModuleExamSet/_ModuleExamSet.cshtml
source/Nidan/Nidan/Views/Shared/_Layout.cshtml

Activity & ActivityTask List Changes V1.4

Activity & ActivityTask List Changes V1.4

---

source/Nidan/Nidan.Business/Enum/EventApproveState.cs
source/Nidan/Nidan.Business/Nidan.Business.csproj
source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan.Data/Models/NidanDatabase.cs
source/Nidan/Nidan.Entity/Event.cs
source/Nidan/Nidan.Entity/EventApproveState.cs
source/Nidan/Nidan.Entity/Nidan.Entity.csproj
source/Nidan/Nidan.Entity/Partials/Event.cs
source/Nidan/Nidan/Controllers/ActivityController.cs
source/Nidan/Nidan/Controllers/ActivityTaskController.cs
source/Nidan/Nidan/Controllers/EventController.cs
source/Nidan/Nidan/Models/ActivityTaskViewModel.cs
source/Nidan/Nidan/Models/ActivityViewModel.cs
source/Nidan/Nidan/Models/EventViewModel.cs
source/Nidan/Nidan/Nidan.csproj
source/Nidan/Nidan/Scripts/Angular/Controllers/EventController.js
source/Nidan/Nidan/Scripts/Angular/Services/EventService.js
source/Nidan/Nidan/Views/Activity/ActivityTaskList.cshtml
source/Nidan/Nidan/Views/Activity/ViewActivity.cshtml
source/Nidan/Nidan/Views/ActivityTask/Index.cshtml
source/Nidan/Nidan/Views/ActivityTask/ViewActivity.cshtml
source/Nidan/Nidan/Views/ActivityTask/ViewTask.cshtml
source/Nidan/Nidan/Views/ActivityTask/_ActivityTaskByActivityId.cshtml
source/Nidan/Nidan/Views/Event/Create.cshtml
source/Nidan/Nidan/Views/Event/Edit.cshtml
source/Nidan/Nidan/Views/Event/Index.cshtml

Activity Management & Event Create & Edit Changes

Activity Management & Event Create & Edit Changes

---

source/Nidan/Nidan.Business/Interfaces/INidanBusinessService.cs
source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan.Data/Interfaces/INidanDataService.cs
source/Nidan/Nidan.Data/Models/NidanDatabase.cs
source/Nidan/Nidan.Data/NidanDataService.cs
source/Nidan/Nidan.Entity/CandidateAttemptedQuestionAnswerGrid.cs
source/Nidan/Nidan.Entity/Nidan.Entity.csproj
source/Nidan/Nidan/Controllers/CandidateAssessmentQuestionAnswerController.cs
source/Nidan/Nidan/Nidan.csproj
source/Nidan/Nidan/Scripts/Angular/Controllers/AssesmentController.js
source/Nidan/Nidan/Scripts/Angular/Services/AssesmentService.js
source/Nidan/Nidan/Views/Assessment/AssessmentByUser.cshtml
source/Nidan/Nidan/Views/CandidateAssessmentQuestionAnswer/CandidateAssessmentDetail.cshtml
source/Nidan/Nidan/Views/CandidateAssessmentQuestionAnswer/CandidateAssessmentQuestionAnswerSet.cshtml
source/Nidan/Nidan/Views/CandidateAssessmentQuestionAnswer/CandidateAttemptedQuestionAnswer.cshtml

Trainer Side Candidate Assessment UI

Trainer Side Candidate Assessment UI

---

source/Nidan/Nidan.Data/Models/NidanDatabase.cs
source/Nidan/Nidan.Entity/CandidateAssessment.cs
source/Nidan/Nidan.Entity/CandidateAttemptedQuestionAnswerGrid.cs
source/Nidan/Nidan/Controllers/CandidateAssessmentQuestionAnswerController.cs
source/Nidan/Nidan/Scripts/Angular/Controllers/AssesmentController.js
source/Nidan/Nidan/Scripts/Angular/Services/AssesmentService.js
source/Nidan/Nidan/Views/CandidateAssessmentQuestionAnswer/CandidateAttemptedQuestionAnswer.cshtml

Total Mark Obtained Update

---

source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan.Data/Models/NidanDatabase.cs
source/Nidan/Nidan.Entity/EventManagement.cs
source/Nidan/Nidan.Entity/EventManagementGrid.cs

EventManagement Issue Resolved

EventManagement Issue Resolved

---

source/Nidan/Nidan/Scripts/Angular/Controllers/AssesmentController.js
source/Nidan/Nidan/Views/CandidateAssessmentQuestionAnswer/CandidateAssessmentQuestionAnswerSet.cshtml
source/Nidan/Nidan/Views/CandidateAssessmentQuestionAnswer/CandidateAttemptedQuestionAnswer.cshtml

Trainer Assessment Changes

---

source/Nidan/Nidan.Business/Enum/EventFunctionType.cs
source/Nidan/Nidan.Business/Interfaces/INidanBusinessService.cs
source/Nidan/Nidan.Business/Nidan.Business.csproj
source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan.Data/Interfaces/INidanDataService.cs
source/Nidan/Nidan.Data/Models/NidanDatabase.cs
source/Nidan/Nidan.Data/NidanDataService.cs
source/Nidan/Nidan.Entity/EventManagementGrid.cs
source/Nidan/Nidan.Entity/Nidan.Entity.csproj
source/Nidan/Nidan/Controllers/EventController.cs

Event Changes

---

source/Nidan/Nidan.Data/Models/NidanDatabase.cs
source/Nidan/Nidan.Entity/EventManagementGrid.cs
source/Nidan/Nidan/Controllers/EventController.cs
source/Nidan/Nidan/Controllers/EventManagementController.cs
source/Nidan/Nidan/Nidan.csproj
source/Nidan/Nidan/Scripts/Angular/Services/BrainstormingService.js
source/Nidan/Nidan/Views/BatchPlanner/Create.cshtml
source/Nidan/Nidan/Views/Event/_BrainStorming.cshtml

EventManagementGrid

---

source/Nidan/Nidan.Business/Interfaces/INidanBusinessService.cs
source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan.Data/Interfaces/INidanDataService.cs
source/Nidan/Nidan.Data/Models/NidanDatabase.cs
source/Nidan/Nidan.Data/NidanDataService.cs
source/Nidan/Nidan.Entity/Centre.cs
source/Nidan/Nidan.Entity/Company.cs
source/Nidan/Nidan.Entity/FixAsset.cs
source/Nidan/Nidan.Entity/Nidan.Entity.csproj
source/Nidan/Nidan.Entity/Organisation.cs
source/Nidan/Nidan/Controllers/CompanyController.cs
source/Nidan/Nidan/Models/CompanyViewModel.cs
source/Nidan/Nidan/Nidan.csproj
source/Nidan/Nidan/Scripts/Angular/Controllers/CompanyController.js
source/Nidan/Nidan/Scripts/Angular/Controllers/FixAssetMappingController.js
source/Nidan/Nidan/Scripts/Angular/Services/CompanyService.js
source/Nidan/Nidan/Views/BankDeposite/Index.cshtml
source/Nidan/Nidan/Views/Company/Create.cshtml
source/Nidan/Nidan/Views/Company/Edit.cshtml
source/Nidan/Nidan/Views/Company/Index.cshtml
source/Nidan/Nidan/Views/Company/_Company.cshtml
source/Nidan/Nidan/Views/FixAssetMapping/_AssignFixAssetMapping.cshtml
source/Nidan/Nidan/Views/FixAssetMapping/_UpdateStatusFixAssetMapping.cshtml
source/Nidan/Nidan/Views/Shared/_Layout.cshtml

Fix Assest Completed with testing and company edit

Fix Assest Completed with testing and company edit

---

source/Nidan/Nidan.Business/Interfaces/INidanBusinessService.cs
source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan.Data/Interfaces/INidanDataService.cs
source/Nidan/Nidan.Data/Models/NidanDatabase.cs
source/Nidan/Nidan.Data/NidanDataService.cs
source/Nidan/Nidan.Entity/Centre.cs
source/Nidan/Nidan.Entity/Company.cs
source/Nidan/Nidan.Entity/CompanyBranch.cs
source/Nidan/Nidan.Entity/CompanyBranchGrid.cs
source/Nidan/Nidan.Entity/CompanyFollowUp.cs
source/Nidan/Nidan.Entity/CompanyFollowUpHistory.cs
source/Nidan/Nidan.Entity/Nidan.Entity.csproj
source/Nidan/Nidan.Entity/Organisation.cs
source/Nidan/Nidan.Entity/Sector.cs
source/Nidan/Nidan/Controllers/CompanyBranchController.cs
source/Nidan/Nidan/Controllers/CompanyController.cs
source/Nidan/Nidan/Controllers/CompanyFollowUpController.cs
source/Nidan/Nidan/Models/CompanyBranchViewModel.cs
source/Nidan/Nidan/Models/CompanyFollowUpViewModel.cs
source/Nidan/Nidan/Nidan.csproj
source/Nidan/Nidan/Scripts/Angular/Controllers/CompanyController.js
source/Nidan/Nidan/Scripts/Angular/Services/CompanyService.js
source/Nidan/Nidan/Views/Company/Edit.cshtml
source/Nidan/Nidan/Views/Company/_Company.cshtml
source/Nidan/Nidan/Views/CompanyBranch/Create.cshtml
source/Nidan/Nidan/Views/CompanyBranch/Edit.cshtml
source/Nidan/Nidan/Views/CompanyBranch/_CompanyBranch.cshtml

Company Branch View and FollowUp

Company Branch View and FollowUp

---

source/Nidan/Nidan.Business/Interfaces/INidanBusinessService.cs
source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan.Data/Interfaces/INidanDataService.cs
source/Nidan/Nidan.Data/Models/NidanDatabase.cs
source/Nidan/Nidan.Data/NidanDataService.cs
source/Nidan/Nidan.Entity/CompanyBranch.cs
source/Nidan/Nidan.Entity/CompanyFollowUp.cs
source/Nidan/Nidan.Entity/CompanyFollowUpGrid.cs
source/Nidan/Nidan.Entity/CompanyFollowUpHistoryGrid.cs
source/Nidan/Nidan.Entity/Nidan.Entity.csproj
source/Nidan/Nidan/Controllers/CompanyFollowUpController.cs
source/Nidan/Nidan/Models/CompanyFollowUpViewModel.cs
source/Nidan/Nidan/Nidan.csproj
source/Nidan/Nidan/Scripts/Angular/Controllers/CompanyFollowUpController.js
source/Nidan/Nidan/Scripts/Angular/Controllers/CompanyFollowUpHistoryController.js
source/Nidan/Nidan/Scripts/Angular/Services/CompanyFollowUpHistoryService.js
source/Nidan/Nidan/Scripts/Angular/Services/CompanyFollowUpService.js
source/Nidan/Nidan/Views/CompanyBranch/_CompanyBranch.cshtml
source/Nidan/Nidan/Views/CompanyFollowUp/Edit.cshtml
source/Nidan/Nidan/Views/CompanyFollowUp/Index.cshtml
source/Nidan/Nidan/Views/CompanyFollowUp/_CompanyFollowUp.cshtml
source/Nidan/Nidan/Views/CompanyFollowUp/_CompanyFollowUpHistory.cshtml
source/Nidan/Nidan/Views/FollowUp/Index.cshtml
source/Nidan/Nidan/Views/Shared/_Layout.cshtml

Company Create Edit and FollowUps Completed

Company Create Edit and FollowUps Completed

---

source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan.Entity/CentrePettyCash.cs
source/Nidan/Nidan.Entity/Personnel.cs
source/Nidan/Nidan/Controllers/BaseController.cs
source/Nidan/Nidan/Controllers/CentrePettyCashController.cs
source/Nidan/Nidan/Models/BaseViewModel.cs
source/Nidan/Nidan/Views/Shared/_Layout.cshtml

Franchise Implemented (UI Changes)

Franchise Implemented (UI Changes)

---

source/Nidan/Nidan.Business/Interfaces/INidanBusinessService.cs
source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan.Data/Interfaces/INidanDataService.cs
source/Nidan/Nidan.Data/Models/NidanDatabase.cs
source/Nidan/Nidan.Data/NidanDataService.cs
source/Nidan/Nidan.Entity/Admission.cs
source/Nidan/Nidan.Entity/Batch.cs
source/Nidan/Nidan.Entity/CandidatePrePlacementActivity.cs
source/Nidan/Nidan.Entity/CandidatePrePlacementActivityGrid.cs
source/Nidan/Nidan.Entity/Centre.cs
source/Nidan/Nidan.Entity/Nidan.Entity.csproj
source/Nidan/Nidan.Entity/Organisation.cs
source/Nidan/Nidan/Controllers/CandidatePrePlacementActivityController.cs
source/Nidan/Nidan/Models/CandidatePrePlacementActivityViewModel.cs
source/Nidan/Nidan/Nidan.csproj
source/Nidan/Nidan/Scripts/Angular/Controllers/CandidatePrePlacementActivityController.js
source/Nidan/Nidan/Scripts/Angular/Services/CandidatePrePlacementActivityService.js
source/Nidan/Nidan/Views/CandidatePrePlacementActivity/Index.cshtml

Candidate Pre Placement Code

---

source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan/Controllers/CandidateAssessmentQuestionAnswerController.cs
source/Nidan/Nidan/Controllers/ReportController.cs
source/Nidan/Nidan/Models/CandidateAssessmentQuestionAnswerViewModel.cs
source/Nidan/Nidan/Views/CandidateAssessmentQuestionAnswer/CandidateAssessmentQuestionAnswerSet.cshtml

Report Changes

---

source/Nidan/Nidan/Views/Expense/Create.cshtml

Expense Submit Button Changes

---

source/Nidan/Nidan.Business/Interfaces/INidanBusinessService.cs
source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan.Data/Interfaces/INidanDataService.cs
source/Nidan/Nidan.Data/Models/NidanDatabase.cs
source/Nidan/Nidan.Data/NidanDataService.cs
source/Nidan/Nidan.Entity/CasteCategory.cs
source/Nidan/Nidan.Entity/Centre.cs
source/Nidan/Nidan.Entity/City.cs
source/Nidan/Nidan.Entity/Course.cs
source/Nidan/Nidan.Entity/District.cs
source/Nidan/Nidan.Entity/Enquiry.cs
source/Nidan/Nidan.Entity/FollowUp.cs
source/Nidan/Nidan.Entity/HowDidYouKnowAbout.cs
source/Nidan/Nidan.Entity/LeadSource.cs
source/Nidan/Nidan.Entity/Nidan.Entity.csproj
source/Nidan/Nidan.Entity/Occupation.cs
source/Nidan/Nidan.Entity/Organisation.cs
source/Nidan/Nidan.Entity/Partials/Enquiry.cs
source/Nidan/Nidan.Entity/Qualification.cs
source/Nidan/Nidan.Entity/Religion.cs
source/Nidan/Nidan.Entity/State.cs
source/Nidan/Nidan.Entity/Taluka.cs
source/Nidan/Nidan/Controllers/EnquiryController.cs
source/Nidan/Nidan/Controllers/HomeController.cs
source/Nidan/Nidan/Models/EnquiryViewModel.cs
source/Nidan/Nidan/Views/Enquiry/_Enquiry.cshtml

V1.5 enquiry changes

---

source/Nidan/Nidan.Data/Models/NidanDatabase.cs
source/Nidan/Nidan.Entity/CasteCategory.cs
source/Nidan/Nidan.Entity/Enquiry.cs
source/Nidan/Nidan.Entity/EnquiryDataGrid.cs
source/Nidan/Nidan.Entity/EnquirySearchField.cs
source/Nidan/Nidan.Entity/HowDidYouKnowAbout.cs
source/Nidan/Nidan.Entity/Occupation.cs
source/Nidan/Nidan.Entity/Religion.cs
source/Nidan/Nidan.Entity/Sector.cs

Enquiry Create Done with changes

Enquiry Create Done with changes

---

source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan/Controllers/EnquiryController.cs

DB Script Counseling Table

---

source/Nidan/Nidan.Business/Interfaces/INidanBusinessService.cs
source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan.Data/Interfaces/INidanDataService.cs
source/Nidan/Nidan.Data/Models/NidanDatabase.cs
source/Nidan/Nidan.Data/NidanDataService.cs
source/Nidan/Nidan.Entity/ExpenseHeaderGrid.cs
source/Nidan/Nidan.Entity/Nidan.Entity.csproj
source/Nidan/Nidan/Controllers/ExpenseController.cs
source/Nidan/Nidan/Controllers/ReportController.cs
source/Nidan/Nidan/Scripts/Angular/Controllers/ExpenseController.js
source/Nidan/Nidan/Scripts/Angular/Controllers/ReportController.js
source/Nidan/Nidan/Scripts/Angular/Services/ExpenseService.js
source/Nidan/Nidan/Scripts/Angular/Services/ReportService.js
source/Nidan/Nidan/Views/BankDeposite/View.cshtml
source/Nidan/Nidan/Views/Expense/Index.cshtml
source/Nidan/Nidan/Views/Report/ExpenseDetailReport.cshtml
source/Nidan/Nidan/Views/Shared/_Layout.cshtml

ExpenseHeaderGrid Added

---

source/Nidan/Nidan.Business/Interfaces/INidanBusinessService.cs
source/Nidan/Nidan.Business/Models/ExpenseHeaderSummaryReport.cs
source/Nidan/Nidan.Business/Nidan.Business.csproj
source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan.Data/Models/NidanDatabase.cs
source/Nidan/Nidan.Data/NidanDataService.cs
source/Nidan/Nidan.Entity/ExpenseHeaderGrid.cs
source/Nidan/Nidan.Entity/MobilizationDataGrid.cs
source/Nidan/Nidan.Entity/Nidan.Entity.csproj
source/Nidan/Nidan.Entity/Partials/Expense.cs
source/Nidan/Nidan/Controllers/BankDepositeController.cs
source/Nidan/Nidan/Controllers/EnquiryController.cs
source/Nidan/Nidan/Controllers/ExpenseController.cs
source/Nidan/Nidan/Nidan.csproj
source/Nidan/Nidan/Scripts/Angular/Controllers/AdmissionController.js
source/Nidan/Nidan/Scripts/Angular/Controllers/ExpenseController.js
source/Nidan/Nidan/Scripts/Angular/Controllers/MobilizationController.js
source/Nidan/Nidan/Views/BankDeposite/View.cshtml
source/Nidan/Nidan/Views/BankDeposite/_BankDeposite.cshtml
source/Nidan/Nidan/Views/Enquiry/Index.cshtml
source/Nidan/Nidan/Views/Expense/Index.cshtml
source/Nidan/Nidan/Views/Mobilization/View.cshtml
source/Nidan/Nidan/Views/Report/MobilizationStatistics.cshtml

Mobilization Search and Expense Changes

Mobilization Search and Expense Changes

---

source/Nidan/Nidan/Views/Enquiry/_Enquiry.cshtml
source/Nidan/Nidan/Views/Registration/Create.cshtml
source/Nidan/Nidan/Views/Shared/_Counselling.cshtml
source/Nidan/Nidan/Views/Shared/_Document.cshtml
source/Nidan/Nidan/Views/Shared/_Layout.cshtml

NidanERP v1.5 Deployed Project with DB Script

NidanERP v1.5 Deployed Project with DB Script

---

source/Nidan/Nidan.Business/Interfaces/INidanBusinessService.cs
source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan/Controllers/ActivityAssigneeGroupController.cs
source/Nidan/Nidan/Controllers/HomeController.cs
source/Nidan/Nidan/Controllers/OtherFeeController.cs
source/Nidan/Nidan/Views/Shared/_Layout.cshtml

Graph Changes

---

source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan.Data/NidanDataService.cs
source/Nidan/Nidan/Controllers/CourseInstallmentController.cs
source/Nidan/Nidan/Controllers/ExpenseController.cs
source/Nidan/Nidan/Models/ExpenseViewModel.cs
source/Nidan/Nidan/Scripts/Angular/Controllers/ExpenseController.js
source/Nidan/Nidan/Views/Admission/Create.cshtml
source/Nidan/Nidan/Views/CourseInstallment/Index.cshtml
source/Nidan/Nidan/Views/Expense/Create.cshtml
source/Nidan/Nidan/Views/Expense/Edit.cshtml
source/Nidan/Nidan/Views/Expense/Index.cshtml
source/Nidan/Nidan/Views/Expense/_Expense.cshtml
source/Nidan/Nidan/Views/Registration/Create.cshtml
source/Nidan/Nidan/Views/Registration/Index.cshtml
source/Nidan/Nidan/Views/Shared/_Layout.cshtml

Expense Changes

---

source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan.Data/Models/NidanDatabase.cs
source/Nidan/Nidan.Entity/ActivityTask.cs
source/Nidan/Nidan/Controllers/ActivityTaskController.cs
source/Nidan/Nidan/Models/ActivityTaskViewModel.cs
source/Nidan/Nidan/Nidan.csproj
source/Nidan/Nidan/Nidan.csproj.user
source/Nidan/Nidan/Scripts/Angular/Controllers/ActivityTaskController.js
source/Nidan/Nidan/Views/ActivityTask/Edit.cshtml
source/Nidan/Nidan/Views/ActivityTask/_ActivityTask.cshtml
source/Nidan/Nidan/Views/ActivityTask/_AddTaskStatus.cshtml

Activity Changes

---

source/Nidan/Nidan.Business/Interfaces/INidanBusinessService.cs
source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan.Data/Interfaces/INidanDataService.cs
source/Nidan/Nidan.Data/Models/NidanDatabase.cs
source/Nidan/Nidan.Data/NidanDataService.cs
source/Nidan/Nidan.Entity/CandidatePrePlacementDataGrid.cs
source/Nidan/Nidan.Entity/CandidatePrePlacementReportGrid.cs
source/Nidan/Nidan.Entity/Nidan.Entity.csproj
source/Nidan/Nidan/Controllers/BatchPrePlacementController.cs
source/Nidan/Nidan/Models/BatchPrePlacementViewModel.cs
source/Nidan/Nidan/Models/CandidatePrePlacementReportViewModel.cs
source/Nidan/Nidan/Nidan.csproj
source/Nidan/Nidan/Scripts/Angular/Controllers/BatchPrePlacementController.js
source/Nidan/Nidan/Scripts/Angular/Services/BatchPrePlacementService.js
source/Nidan/Nidan/Views/BatchPrePlacement/CandidatePrePlacementData.cshtml
source/Nidan/Nidan/Views/BatchPrePlacement/View.cshtml
source/Nidan/Nidan/Views/BatchPrePlacement/_BatchPrePlacement.cshtml
source/Nidan/Nidan/Views/BatchPrePlacement/_CandidatePrePlacementReport.cshtml
source/Nidan/Nidan/Views/Shared/_Layout.cshtml

Batch Pre-Placement

---

source/Nidan/Nidan.Business/Interfaces/INidanBusinessService.cs
source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan.Data/Interfaces/INidanDataService.cs
source/Nidan/Nidan.Data/Models/NidanDatabase.cs
source/Nidan/Nidan.Data/NidanDataService.cs
source/Nidan/Nidan.Entity/ActivityTaskDataGrid.cs
source/Nidan/Nidan.Entity/ActivityTaskState.cs
source/Nidan/Nidan.Entity/ActivityTaskStateDataGrid.cs
source/Nidan/Nidan.Entity/Nidan.Entity.csproj
source/Nidan/Nidan/Controllers/ActivityTaskController.cs
source/Nidan/Nidan/Models/ActivityTaskViewModel.cs
source/Nidan/Nidan/Views/ActivityAssigneeGroup/Index.cshtml
source/Nidan/Nidan/Views/ActivityTask/Create.cshtml
source/Nidan/Nidan/Views/ActivityTask/Edit.cshtml
source/Nidan/Nidan/Views/ActivityTask/_ActivityTaskByActivityId.cshtml

Activity With Email & Bug Fixes

Activity With Email & Bug Fixes

---

source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan.Data/Models/NidanDatabase.cs
source/Nidan/Nidan.Entity/ActivityAssigneeGroup.cs
source/Nidan/Nidan.Entity/ActivityTaskDataGrid.cs
source/Nidan/Nidan.Entity/ActivityTaskStateDataGrid.cs
source/Nidan/Nidan/Controllers/ActivityAssigneeGroupController.cs
source/Nidan/Nidan/Models/ActivityAssigneeGroupViewModel.cs
source/Nidan/Nidan/Views/ActivityAssigneeGroup/_ActivityAssigneeGroup.cshtml
source/Nidan/Nidan/Views/Home/Index.cshtml
source/Nidan/Nidan/Views/Shared/_AdminLayout.cshtml
source/Nidan/Nidan/Views/Shared/_Layout.cshtml
source/Nidan/Nidan/Web.config

Activity Deploy with DB

---

source/Nidan/Nidan/Controllers/BatchPrePlacementController.cs
source/Nidan/Nidan/Scripts/Angular/Controllers/BatchPrePlacementController.js
source/Nidan/Nidan/Views/BatchPrePlacement/CandidatePrePlacementData.cshtml
source/Nidan/Nidan/Views/BatchPrePlacement/Edit.cshtml
source/Nidan/Nidan/Views/BatchPrePlacement/_BatchPrePlacement.cshtml
source/Nidan/Nidan/Views/Shared/_AdminLayout.cshtml
source/Nidan/Nidan/Views/Shared/_Layout.cshtml
source/Nidan/Nidan/Web.config

Batch Pre Placement Small Changes

Batch Pre Placement Small Changes

---

source/Nidan/Nidan.Business/NidanBusinessService.cs
source/Nidan/Nidan/Controllers/BatchPrePlacementController.cs
source/Nidan/Nidan/Scripts/Angular/Controllers/BatchPrePlacementController.js
source/Nidan/Nidan/Views/BatchPrePlacement/Edit.cshtml
source/Nidan/Nidan/Views/BatchPrePlacement/_CandidatePrePlacementActivity.cshtml

BatchPrePlacement changes
